language: java
sudo: false # faster builds

env:
  - CODECOV_TOKEN="7a4d21ed-0645-4212-bc66-b14184708d2c"

jdk:
  - oraclejdk12
  - openjdk11
  - oraclejdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 mvn clean install -DskipTests=false -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master