language: java
sudo: false # faster builds

jdk:
  - oraclejdk12
  - openjdk11
  - oraclejdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 mvn clean install -DskipTests=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master